name: Build and Release Standalone

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Application
      run: dotnet build --configuration Release

    - name: Publish Standalone
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true

    - name: Archive Build
      uses: actions/upload-artifact@v3
      with:
        name: standalone-release
        path: bin\Release\net7.0\win-x64\publish\*

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: v1.0.0
        name: "Standalone Release"
        artifacts: bin\Release\net7.0\win-x64\publish\*
